### PR TITLE
Add 'joined' field to cast in DateTime

### PR DESCRIPTION
**Pull request by tolbon**

### CODE REVIEW

**Comment by tolbon** [comment]
Yeah I can do that,

This is an example of Workplace by Facebook but that's work for Facebook Consumer 
[Workplace Docs](https://developers.facebook.com/docs/workplace/integrations/custom-integrations/reference/group) in "Example" section you see
```
GET graph.facebook.com
  /{group-id}/members?fields=name,id,joined
```

**Comment by SammyK** [comment]
Hey @yguedidi! If you approve this, I'll update the changelog. :)

**Comment by yguedidi** [comment]
@SammyK I approved, but regarding git, I'm more in favor the rebase strategy than the merge strategy to update a PR: it provides a cleaner git history :)

**Comment by SammyK** [comment]
@yguedidi Thanks! I'm also a big rebase fan. I was just testing out this button:

screen shot 2018-07-03 at 6 01 46 pm

I guess I know what it does now! Lol. :)

**Pull request merged**
