### PR TITLE
getFanCount() method to GraphPage. (get pagelikes)

### PR DESCRIPTION
**Pull request by eddieace**
The GraphPage object was missing a get method for fan_count AKA page likes. So I added it.

### CODE REVIEW

**Comment by yguedidi** [comment]
Thanks @eddieace for your PR and sorry for the delay! Can you please rebase your PR on 5.x and update the changelog file? Thanks!

**Comment by eddieace** [comment]
Why does this fail on HHVM

**Comment by yguedidi** [comment]
@eddieace I really don't know, I'm not an HHVM expert :(

**Comment by yguedidi** [comment]
@eddieace mabye close this PR and start a new one on latest 5.x branch?

**Pull request merged**
