### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by theDanielK**
Random spelling thing. Eye caught it.

### CODE REVIEW

**Comment by yguedidi** [comment]
@theDanielK Thanks for this fix! You should sign for the CLA to get you PR merged and become a contributor :)

**Comment by theDanielK** [comment]
@yguedidi I've signed up. I'd love to actually get involved (rather than fixing spelling things :P )

**Comment by yguedidi** [comment]
Thanks @theDanielK!!

**Comment by SammyK** [comment]
Thanks & welcome @theDanielK! Looking forward to more contributions! :)

**Pull request merged**
