### PR TITLE
Update FacebookUrlDetectionHandler.php

### PR DESCRIPTION
**Pull request by rostalevicek**
Fix redirect_uri verification when extended parameters are part of URI.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by SammyK** [comment]
Thanks @rostalevicek! Can you create a test for this as well? After you sign the CLA, I'll pull this in. :)

**Comment by yguedidi** [comment]
@rostalevicek why this change?

**Comment by SammyK** [comment]
Hey @rostalevicek! I'm curious what this is addressing as well now that I look in more detail at it. The query part of the URL [should already be handled gracefully by the SDK](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L225). Are you getting a specific error? Can you provide any relevant code for this one? :)

**Comment by SammyK** [comment]
Hey @rostalevicek! I'm closing this for now, but if you want us to reopen, feel free to chime in! :)

**Pull request closed without merging**
