### PR TITLE
Clean up documentation files

### PR DESCRIPTION
**Pull request by carusogabriel**
I've cleaned up our documentation, by removing whitespaces spaces and extra lines :smile:

### CODE REVIEW

**Comment by carusogabriel** [comment]
@yguedidi I’m out of home now, so I’ve merged via Mobile 😁

**Comment by yguedidi** [comment]
@carusogabriel I'll wait for you to be at home so you can rebase :)
Not need for a "Merge branch '5.x' into docs" commit in this PR, in order to keep the history clean

**Comment by carusogabriel** [comment]
@yguedidi Done :smile:

**Comment by yguedidi** [comment]
Thanks you @carusogabriel for this clean up! :)

**Pull request merged**
