### PR TITLE
Added possibility to choose the login display type

### PR DESCRIPTION
**Pull request by jbereziecki**
I find it necessary to be able to choose the Facebook Login display type.

### CODE REVIEW

**Comment by yguedidi** [comment]
@jbereziecki thank you for this PR!! And sorry for the delay..
Wahou! Complete PR with code, tests and doc!
Unfortunatly, according the [Facebook doc](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/) looks like the `display` parameters in not supported anymore, so I'm closing this.
Feel free to contribute to the SDK!

**Comment by jbereziecki** [comment]
@yguedidi 
Thanks for finally looking into this.
Although not documented, the display type parameter is active when invoking the OAuth dialog under https://www.facebook.com/v2.10/dialog/oauth

I have just tested it and the different display types result in different dialogs being rendered. I need this a lot in my application.

**Comment by yguedidi** [comment]
@jbereziecki how you test it? I just tested it using the Graph API Explorer, and here are what I saw:

- `async` and `iframe` don't work, I get an error
- `touch` and `wap` looks like exactly like the `page` display
- `popup` is working and has a different look than `page`

Based on that, only `page` and `popup` are useful.

So then, why would you like to use the `popup` display while it was made for the JS SDK I guess :)
What's your use case?

**Comment by jbereziecki** [comment]
@yguedidi I tested it manually invoking the OAuth dialog, and for me it seems, that async returns 500 indeed, iframe requires public_profile scope, the rest of them is exactly as you described.

I need to be able to select the display type because we are invoking the login dialog from different clients - it might be either a desktop app (the page display is fine here) or a popup in a web app (we need the popup display here to strip down the FB footer etc.).

I might limit the display type enumeration to only contain page and popup if it's the case.

**Comment by yguedidi** [comment]
@jbereziecki just to understand better, why don't you use the Javascript SDK to login using a popup?
Except if you app already live inside a popup, but then, it's really a specific usage. So I think we won't support it in the SDK.
Why don't you extend the `FacebookRedirectLoginHelper`? :)

**Comment by jbereziecki** [comment]
@yguedidi Javascript SDK is not suitable for the desktop client and duplicating the logic is a bad idea.

I'll just extend the SDK locally, wanted to avoid it tho due to possible later incompatibilities. Thanks for your support.

**Pull request closed without merging**
