### PR TITLE
Consistent coding styles

### PR DESCRIPTION
**Pull request by voyula**

### CODE REVIEW

**Comment by SammyK** [comment]
@voyula Thanks for the PR! I'm -1 on this one since the SDK uses the PSR-2 coding standard and is enforced in the build with PHP CodeSniffer. I'll let @yguedidi have the final call. :)

**Comment by yguedidi** [comment]
@SammyK I'm +0 for this: not that useful for most of people, but I see the benefits:

- cover more that just PHP and PSR-2 (markdown, YAML)
- may help users switching between several projects, so potentially several standard

But I think this should target master, as it's something totally new.

@SammyK what do you think after those arguments? :)

**Comment by SammyK** [comment]
@yguedidi Makes sense to me. I'm down for merging it in. :)

@voyula I'm assuming you closed this due to the requirement to sign the CLA? If so, I totally understand. Sorry if that was a blocker for you. That's FB's policy, not ours (@yguedidi are just volunteers who don't work for FB.) But we really appreciate you taking the time to send some contributions. :)

**Comment by ghost** [comment]
@SammyK i'm joined in CLA for you. <3

Thanks for your humbleness.

**Comment by yguedidi** [comment]
@voyula Thanks! Can you please rebase on master and target the master branch so this get merged? :)

**Comment by BinRoq** [comment]
Hello World

**Comment by yguedidi** [comment]
@voyula hi! why closing this without being merged?

**Pull request closed without merging**
