### PR TITLE
Remove PHP5.6 support

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by yguedidi** [comment]
@Nyholm Thanks for this, but tests are broken on HHVM... I would like to work on this, is it OK for you? :)

**Comment by Nyholm** [comment]
The tests are not broken, it is a composer/hhvm issue. I search a bit for a solution but found none. The lastest stable version of HHVM would work, but that is (strangely) not the version we get with "hhvm-nightly".

**Comment by yguedidi** [comment]
@Nyholm I'm closing this, I'm working on HHVM green builds! I kept your first commit in #813 for authorship ;)

**Comment by Nyholm** [comment]
Feel free to close it. 

Thank you. That is very kind of you.

**Pull request closed without merging**
